//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Switch.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Switch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic OSI layer 2 network simulator
        ///
        ///Konstantin Pospelov, 2015.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aging time.
        /// </summary>
        public static string AgingTime {
            get {
                return ResourceManager.GetString("AgingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation.
        /// </summary>
        public static string Animation {
            get {
                return ResourceManager.GetString("Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        public static string Blocked {
            get {
                return ResourceManager.GetString("Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open.
        /// </summary>
        public static string CannotOpen {
            get {
                return ResourceManager.GetString("CannotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save.
        /// </summary>
        public static string CannotSave {
            get {
                return ResourceManager.GetString("CannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change address.
        /// </summary>
        public static string ChangeAddress {
            get {
                return ResourceManager.GetString("ChangeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose port.
        /// </summary>
        public static string ChoosePort {
            get {
                return ResourceManager.GetString("ChoosePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearScheme {
            get {
                return ResourceManager.GetString("ClearScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on device.
        /// </summary>
        public static string ClickOnDevice {
            get {
                return ResourceManager.GetString("ClickOnDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        public static string Computer {
            get {
                return ResourceManager.GetString("Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string ConnectionSpeed {
            get {
                return ResourceManager.GetString("ConnectionSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new scheme.
        /// </summary>
        public static string CreateNewScheme {
            get {
                return ResourceManager.GetString("CreateNewScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default port.
        /// </summary>
        public static string DefaultPort {
            get {
                return ResourceManager.GetString("DefaultPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device with hash code.
        /// </summary>
        public static string DeviceWithHashCode {
            get {
                return ResourceManager.GetString("DeviceWithHashCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5m.
        /// </summary>
        public static string FiveMins {
            get {
                return ResourceManager.GetString("FiveMins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5s.
        /// </summary>
        public static string FiveSecs {
            get {
                return ResourceManager.GetString("FiveSecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15s.
        /// </summary>
        public static string FiveteenSecs {
            get {
                return ResourceManager.GetString("FiveteenSecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forwarded.
        /// </summary>
        public static string Forwarded {
            get {
                return ResourceManager.GetString("Forwarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame.
        /// </summary>
        public static string Frame {
            get {
                return ResourceManager.GetString("Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string FrameAction {
            get {
                return ResourceManager.GetString("FrameAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame transmission.
        /// </summary>
        public static string FrameTransmission {
            get {
                return ResourceManager.GetString("FrameTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate address.
        /// </summary>
        public static string GenerateAddress {
            get {
                return ResourceManager.GetString("GenerateAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string h {
            get {
                return ResourceManager.GetString("h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspires.
        /// </summary>
        public static string Inspires {
            get {
                return ResourceManager.GetString("Inspires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        public static string Interval {
            get {
                return ResourceManager.GetString("Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid attribute.
        /// </summary>
        public static string InvalidAttribute {
            get {
                return ResourceManager.GetString("InvalidAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not a computer.
        /// </summary>
        public static string IsNotComputer {
            get {
                return ResourceManager.GetString("IsNotComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not a switch.
        /// </summary>
        public static string IsNotSwitch {
            get {
                return ResourceManager.GetString("IsNotSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load scheme.
        /// </summary>
        public static string LoadScheme {
            get {
                return ResourceManager.GetString("LoadScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string m {
            get {
                return ResourceManager.GetString("m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address table.
        /// </summary>
        public static string MacTable {
            get {
                return ResourceManager.GetString("MacTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        public static string ms {
            get {
                return ResourceManager.GetString("ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New scheme.
        /// </summary>
        public static string NewScheme {
            get {
                return ResourceManager.GetString("NewScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No free ports to connect.
        /// </summary>
        public static string NoFreePortsToConnect {
            get {
                return ResourceManager.GetString("NoFreePortsToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not chosen.
        /// </summary>
        public static string NotChosen {
            get {
                return ResourceManager.GetString("NotChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid MAC address.
        /// </summary>
        public static string NotValidMacAddress {
            get {
                return ResourceManager.GetString("NotValidMacAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name.
        /// </summary>
        public static string NotValidName {
            get {
                return ResourceManager.GetString("NotValidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of ports.
        /// </summary>
        public static string NumberOfPorts {
            get {
                return ResourceManager.GetString("NumberOfPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1m.
        /// </summary>
        public static string OneMin {
            get {
                return ResourceManager.GetString("OneMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause frame transmission.
        /// </summary>
        public static string PauseTransmission {
            get {
                return ResourceManager.GetString("PauseTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC.
        /// </summary>
        public static string PC {
            get {
                return ResourceManager.GetString("PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointer.
        /// </summary>
        public static string Pointer {
            get {
                return ResourceManager.GetString("Pointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to port number isn&apos;t in the switch range.
        /// </summary>
        public static string PortNumberIsNotInSwitchRange {
            get {
                return ResourceManager.GetString("PortNumberIsNotInSwitchRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port state.
        /// </summary>
        public static string PortState {
            get {
                return ResourceManager.GetString("PortState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset selection.
        /// </summary>
        public static string ResetSelection {
            get {
                return ResourceManager.GetString("ResetSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume frame transmission.
        /// </summary>
        public static string ResumeTransmission {
            get {
                return ResourceManager.GetString("ResumeTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root switch.
        /// </summary>
        public static string RootSwitch {
            get {
                return ResourceManager.GetString("RootSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string s {
            get {
                return ResourceManager.GetString("s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100 Mbit/s.
        /// </summary>
        public static string S100Mbps {
            get {
                return ResourceManager.GetString("S100Mbps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 Gbit/s.
        /// </summary>
        public static string S10Gbps {
            get {
                return ResourceManager.GetString("S10Gbps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 Mbit/s.
        /// </summary>
        public static string S10Mbps {
            get {
                return ResourceManager.GetString("S10Mbps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16 Mbit/s.
        /// </summary>
        public static string S16Mbps {
            get {
                return ResourceManager.GetString("S16Mbps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Gbit/s.
        /// </summary>
        public static string S1Gbps {
            get {
                return ResourceManager.GetString("S1Gbps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Gbit/s.
        /// </summary>
        public static string S2Gbps {
            get {
                return ResourceManager.GetString("S2Gbps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 Mbit/s.
        /// </summary>
        public static string S4Mbps {
            get {
                return ResourceManager.GetString("S4Mbps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes?.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save scheme.
        /// </summary>
        public static string SaveScheme {
            get {
                return ResourceManager.GetString("SaveScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save scheme as....
        /// </summary>
        public static string SaveSchemeAs {
            get {
                return ResourceManager.GetString("SaveSchemeAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheme.
        /// </summary>
        public static string Scheme {
            get {
                return ResourceManager.GetString("Scheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheme was changed.
        /// </summary>
        public static string SchemeChanged {
            get {
                return ResourceManager.GetString("SchemeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheme files.
        /// </summary>
        public static string SchemeFiles {
            get {
                return ResourceManager.GetString("SchemeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send frame.
        /// </summary>
        public static string SendFrame {
            get {
                return ResourceManager.GetString("SendFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        public static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop frame transmission.
        /// </summary>
        public static string StopTransmission {
            get {
                return ResourceManager.GetString("StopTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanning Tree Protocol.
        /// </summary>
        public static string STP {
            get {
                return ResourceManager.GetString("STP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch.
        /// </summary>
        public static string Switch {
            get {
                return ResourceManager.GetString("Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10m.
        /// </summary>
        public static string TenMins {
            get {
                return ResourceManager.GetString("TenMins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30s.
        /// </summary>
        public static string ThirtySecs {
            get {
                return ResourceManager.GetString("ThirtySecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Network Simulator.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmitted frames.
        /// </summary>
        public static string TransmittedFrames {
            get {
                return ResourceManager.GetString("TransmittedFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2m.
        /// </summary>
        public static string TwoMins {
            get {
                return ResourceManager.GetString("TwoMins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown device with hash code.
        /// </summary>
        public static string UnknownDeviceWithHashCode {
            get {
                return ResourceManager.GetString("UnknownDeviceWithHashCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
